base_model: {
  name: 'regular',
  pretrained: True,
  width_mult: 1.0,
  checkpoint: 'models/mobilenetv3/pretrained/mobilenetv3-large-stl10.pth'
}

model: {
  name: 'channel_bottleneck',
  split_position: 5,
  bottleneck_ratio: 1.0,
}
