base_model: {
  pretrained: True,
  width_mult: 1.0,
  checkpoint: 'models/mobilenetv3/pretrained/mobilenetv3-large-stl10.pth'
}

model: {
  name: 'entropy_bottleneck',
  split_position: 7,
  bottleneck_position: 5,
  bottleneck_ratio: 1.0,
  compression_parameter: 50.0

}
