name: "oxford_pets"
classes: ['Wheaten Terrier', 'Egyptian Mau', 'Yorkshire Terrier', 'Bombay', 'Bengal', 'Birman', 'American Bulldog', 'Japanese Chin', 'British Shorthair', 'Samoyed', 'Saint Bernard', 'German Shorthaired', 'Chihuahua', 'English Cocker Spaniel', 'Abyssinian']
